version: "3.8"

services:

  pgdb:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  uk223_backend:
    image: mikkak/uk233_backend
    restart: unless-stopped
    ports:
      - "8091:8080"
    env_file:
      - .env

  uk223_frontend:
      image: mikkak/frontend:1.1
      restart: unless-stopped
      ports:
        - "8006:80"
      env_file:
        - .env