name: test-pipeline

on:
  push:
    branches:
    - main
    - feature/*
    - dev
jobs:
  testi:
    name: test echo
    runs-on: ubuntu-latest
    steps:
    
    
    - name: checkout
      uses: actions/checkout@v2.5.0
      
      
    - name: run run.sh
      run: |
        ./run.sh
